# Configuration File for morph_check


##############################################
# FORMATTING
##############################################

color : true

##############################################
# CHECKS
##############################################

checks:
    neuron_checks:
        - has_basal_dendrite
        - has_axon
        - has_apical_dendrite
        - has_all_nonzero_segment_lengths
        - has_all_nonzero_section_lengths
        - has_all_nonzero_neurite_radii
        - has_nonzero_soma_radius

##############################################
# OPTIONS
##############################################

options:

    # threshold
    has_nonzero_soma_radius         : 0.0
    has_all_nonzero_neurite_radii   : 0.007
    has_all_nonzero_segment_lengths : 0.01
    has_all_nonzero_section_lengths : 0.01

    # tolerance/ratio, method
    has_no_flat_neurites       : [0.1, 'ratio']
